### ISSUE TITLE
View AST  not work

### ISSUE THREAD

**Issue by turn1tup** [github/vscode-codeql#1063]
**Describe the bug**
Hello, the "View AST" is not work. I have try on three windows and one mac os, but all not work.
Can you help me.

**Version**
The CodeQL and VS Code version in which the bug occurs.

Visual Studio Code  v1.63.2
![image](https://user-images.githubusercontent.com/41148379/147456041-fa822134-8ae3-4c07-94d7-b63c213f22f9.png)

CodeQL for Visual Studio Code v1.5.9
![image](https://user-images.githubusercontent.com/41148379/147456079-2e406156-de86-4e06-aafe-b16aef2a3707.png)

codeql version v2.7.3
![image](https://user-images.githubusercontent.com/41148379/147461255-c78c912a-bc17-40b0-919e-9d7c520afbc5.png)

**To reproduce**
I have try lgtm databse "g/knightliao/disconf"  and local databse which I build by mysel, but I can't View AST anyway. 

![image](https://user-images.githubusercontent.com/41148379/147456310-bea5d805-a3df-49da-844a-54837e731fd7.png)

By the way, can you tell me how to use the codeql-cli in command-line to see the AST, output to a data file is ok. 

Thank you !

The error log is :
Cannot view the AST. Please select a valid source file inside a CodeQL database. (codeQL.viewAst)
Error: Cannot view the AST. Please select a valid source file inside a CodeQL database.
	at TemplatePrintAstProvider.getAst (c:\Users\work\.vscode\extensions\github.vscode-codeql-1.5.9\out\contextual\templateProvider.js:98:19)
	at CachedOperation.get (c:\Users\work\.vscode\extensions\github.vscode-codeql-1.5.9\out\helpers.js:291:39)
	at TemplatePrintAstProvider.provideAst (c:\Users\work\.vscode\extensions\github.vscode-codeql-1.5.9\out\contextual\templateProvider.js:88:32)
	at ctx.subscriptions.push.commandRunner_1.commandRunnerWithProgress.cancellable (c:\Users\work\.vscode\extensions\github.vscode-codeql-1.5.9\out\extension.js:588:44)
	at c:\Users\work\.vscode\extensions\github.vscode-codeql-1.5.9\out\commandRunner.js:38:16
	at S._withProgress (d:\software\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:45568)
	at S.withProgress (d:\software\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:45322)
	at Object.withProgress (d:\software\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:30872)
	at withProgress (c:\Users\work\.vscode\extensions\github.vscode-codeql-1.5.9\out\commandRunner.js:37:28)
	at c:\Users\work\.vscode\extensions\github.vscode-codeql-1.5.9\out\commandRunner.js:109:26
	at r._executeContributedCommand (d:\software\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:31080)
	at r.$executeContributedCommand (d:\software\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:31622)
	at t._doInvokeHandler (d:\software\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:13802)
	at t._invokeHandler (d:\software\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:13486)
	at t._receiveRequest (d:\software\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:12148)
	at t._receiveOneMessage (d:\software\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:10826)
	at d:\software\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:8922
	at u.fire (d:\software\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:66:1712)
	at r.fire (d:\software\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:18942)
	at d:\software\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:114:34341
	at u.fire (d:\software\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:66:1712)
	at r.fire (d:\software\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:18942)
	at n._receiveMessage (d:\software\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:23523)
	at d:\software\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:21057
	at u.fire (d:\software\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:66:1712)
	at w.acceptChunk (d:\software\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:15770)
	at d:\software\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:14900
	at Socket.T (d:\software\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:114:13813)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)

**Comment by aeisenberg** [comment]
Are you running this targeting a source file in the current database? From your screenshot, it looks like you are trying to open the AST viewer on a QL file.

The way to make sure of you are running on a proper file is to go to the file explorer and select a file that is inside of one of the databases that you already have imported into the workspace.

**Comment by aeisenberg** [comment]
See [the documentation here](https://codeql.github.com/docs/codeql-for-visual-studio-code/exploring-the-structure-of-your-source-code/).

**Comment by turn1tup** [comment]
I read this document before,but I didn't understand well.Now I know how to do.
After select a database, I should open the source file from vscode workspace "source archive", then I can use the "AST Viewer".
Thank you very much ~!
