### ISSUE TITLE
Broken build on Node v18

### ISSUE THREAD

**Issue by elenatanasoiu** [github/vscode-codeql#1373]
**Description**

Building the extension via `npm run build` breaks on Node v18, but works fine on previous versions. 

Full error output:

```
$ npm run build

> vscode-codeql@1.6.7 build
> gulp

[09:05:19] Requiring external module ts-node/register
[09:05:20] Using gulpfile ~/projects/vscode-codeql/extensions/ql-vscode/gulpfile.ts
[09:05:20] Starting 'default'...
[09:05:20] Starting 'cleanOutput'...
[09:05:20] Finished 'cleanOutput' after 14 ms
[09:05:20] Starting 'compileTypeScript'...
[09:05:20] Starting 'compileTextMateGrammar'...
[09:05:20] Starting 'compileView'...
[09:05:20] Starting 'copyTestData'...
[09:05:20] Starting 'copyViewCss'...
[09:05:20] Finished 'copyTestData' after 205 ms
[09:05:20] Finished 'compileTextMateGrammar' after 318 ms
[09:05:20] Finished 'copyViewCss' after 330 ms
webpack compiled successfully
[09:05:31] Finished 'compileView' after 11 s
[09:05:35] 'compileTypeScript' errored after 15 s
[09:05:35] Error: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer
    at readWasm (/Users/elenatanasoiu/projects/vscode-codeql/extensions/ql-vscode/node_modules/gulp-typescript/node_modules/source-map/lib/read-wasm.js:8:13)
    at wasm (/Users/elenatanasoiu/projects/vscode-codeql/extensions/ql-vscode/node_modules/gulp-typescript/node_modules/source-map/lib/wasm.js:25:16)
    at /Users/elenatanasoiu/projects/vscode-codeql/extensions/ql-vscode/node_modules/gulp-typescript/node_modules/source-map/lib/source-map-consumer.js:264:14
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[09:05:35] 'default' errored after 15 s
```

**To reproduce**

```
cd extensions/ql-vscode
nvm install 18
nvm use 18
npm install
npm run build
```

**Expected behavior**
The build command should complete without errors.

**Additional context**
This passes in codespaces as a codespace currently defaults to v16. Discovered while working on https://github.com/github/vscode-codeql/pull/1369

**Comment by aeisenberg** [comment]
Cause of this error is https://github.com/mozilla/source-map/issues/454, which is a dependency of `source-map-support`. The fix for this error already exists, but it is not in a released version yet.

**Comment by aeisenberg** [comment]
As mentioned in https://github.com/github/vscode-codeql/pull/1378, there's no rush right now to get this fixed, but we do need to address this before vscode releases a version that ships with node 18.

**Comment by elenatanasoiu** [comment]
This is addressed in https://github.com/github/vscode-codeql/pull/1387
