### ISSUE TITLE
Could not find qlpack file for dbscheme ... 

### ISSUE THREAD

**Issue by jtjisgod** [github/vscode-codeql#1935]
**Describe the bug**
I created database from chromium 111 version.
But running quick query and installing dependency is not working.
Above code snippet is my error.
```
Starting NEW query server.
Starting CodeQL query server using CodeQL CLI: /home/jtjisgod/codeql/codeql execute query-server2 --threads 1 -J-Xmx8032M --off-heap-ram=8032 --evaluator-log /home/jtjisgod/.config/Code/User/workspaceStorage/48c3392770c41e28dd4a79d9d2d64bf1/GitHub.vscode-codeql/structured-evaluator-log.json --evaluator-log-level 5 -v --log-to-stderr
CodeQL query server started on PID: 3719
Registering result view navigation commands.
[2023-01-06 16:55:43] This is codeql execute query-server2 --threads 1 -J-Xmx8032M --off-heap-ram=8032 --evaluator-log /home/jtjisgod/.config/Code/User/workspaceStorage/48c3392770c41e28dd4a79d9d2d64bf1/GitHub.vscode-codeql/structured-evaluator-log.json --evaluator-log-level 5 -v --log-to-stderr
[2023-01-06 16:55:43] Creating executor with 1 threads.
[2023-01-06 16:55:43] [SPAMMY] execute query-server2> registerDatabases called with [/home/jtjisgod/Desktop/chromium/codeql/111]
Could not find qlpack file for dbscheme /home/jtjisgod/Desktop/chromium/codeql/111/db-cpp/semmlecode.cpp.dbscheme (codeQL.quickQuery)
Error: Could not find qlpack file for dbscheme /home/jtjisgod/Desktop/chromium/codeql/111/db-cpp/semmlecode.cpp.dbscheme
    at findDbschemePack (/home/jtjisgod/.vscode/extensions/github.vscode-codeql-1.7.7/out/helpers.js:233:11)
    at getQlPackForDbscheme (/home/jtjisgod/.vscode/extensions/github.vscode-codeql-1.7.7/out/helpers.js:262:26)
    at displayQuickQuery (/home/jtjisgod/.vscode/extensions/github.vscode-codeql-1.7.7/out/quick-query.js:82:25)

```

**Version**
CodeQL extension version: 1.7.7 
CodeQL CLI version: 2.11.6 
Platform: linux x64

**Comment by aeisenberg** [comment]
It looks like the core libraries for C++ are not resolvable from the vscode workspace you are using. This is a known bug and we are working on a proper fix. In the meantime, you can do the following:

1. Make sure you have a `qlpack.yml` file defined in your vscode workspace.
2. In this file, add a dependencies block and reference the `codeql/cpp-all` library pack.

Something like this would work:

```
name: my-pack
dependencies:
  codeql/cpp-all: '*'
```

**Comment by jtjisgod** [comment]
Perfact!
It is working.
But I tried more steps.

1. As you said, I added qlpack.yml in my workspace.
2. Installed dependency through codeql cli and codeql-bundle because installing dependency of extension is not working.
3. I checked codeql extension is working through quick query.

Thank you, and Happy new year.
Regards,

**Comment by aeisenberg** [comment]
Thank you for confirming. And glad you could get this working again.
