### ISSUE TITLE
Can't run query anymore

### ISSUE THREAD

**Issue by Nikoms** [github/vscode-codeql#1941]
**Describe the bug**
When I try to run a query in vscode, it fails. It's working 

**Version**
For vscode:
Version: 1.74.2
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:32:21.587Z (2 wks ago)
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.2.0
Sandboxed: No

CodeQL CLI: 2.11.6
CodeQL vscode: github.vscode-codeql-1.7.7

**To reproduce**
Right click on a `.ql`file, click on "run query", it fails. Any query fails

**Expected behavior**
I should get a list of code smells in this case

**Additional context**

I recently update my macos to venture 13.1. I have a m1pro. 
- I tried to uninstall the plugin.
- I tried to uninstall vscode

Any help would be appreciated 🙏

Here are the logs:
```
[2023-01-07 18:24:06] [SPAMMY] execute query-server2> runQuery called with /Users/me/workspace/project1/server/infrastructure/ci/codeql/queries/temp.ql
[2023-01-07 18:24:06] Calling plumbing command: codeql resolve library-path --search-path= --additional-packs=/Users/me/workspace/project1/server --query=/Users/me/workspace/project1/server/infrastructure/ci/codeql/queries/temp.ql --format=json
[2023-01-07 18:24:06] [DETAILS] resolve library-path> Resolving query at normalized path /Users/me/workspace/project1/server/infrastructure/ci/codeql/queries/temp.ql.
[2023-01-07 18:24:06] [DETAILS] resolve library-path> Found enclosing pack 'project1/server' at /Users/me/workspace/project1/server/infrastructure/ci/codeql.
[2023-01-07 18:24:06] [DETAILS] resolve library-path> Adding compilation cache at /Users/me/workspace/project1/server/infrastructure/ci/codeql/.cache.
[2023-01-07 18:24:06] [DETAILS] resolve library-path> QL pack dependencies for /Users/me/workspace/project1/server/infrastructure/ci/codeql found in cache.
[2023-01-07 18:24:06] [DETAILS] resolve library-path> Found dbscheme through QL packs: /Users/me/.codeql/packages/codeql/javascript-all/0.3.6/semmlecode.javascript.dbscheme.
[2023-01-07 18:24:06] Plumbing command codeql resolve library-path completed:
                      {
                        "libraryPath" : [
                          "/Users/me/workspace/project1/server/infrastructure/ci/codeql",
                          "/Users/me/.codeql/packages/codeql/javascript-all/0.3.6"
                        ],
                        "dbscheme" : "/Users/me/.codeql/packages/codeql/javascript-all/0.3.6/semmlecode.javascript.dbscheme",
                        "compilationCache" : [
                          "/Users/me/workspace/project1/server/infrastructure/ci/codeql/.cache"
                        ],
                        "relativeName" : "project1/server/queries/temp.ql",
                        "qlPackName" : "project1/server"
                      }
[2023-01-07 18:24:06] [PROGRESS] execute query-server2> Compiling query plan for /Users/me/workspace/project1/server/infrastructure/ci/codeql/queries/temp.ql.
[2023-01-07 18:24:06] [DETAILS] execute query-server2> Resolving imports for /Users/me/workspace/project1/server/infrastructure/ci/codeql/queries/temp.ql.
[2023-01-07 18:24:06] Resolved file set for /Users/me/workspace/project1/server/infrastructure/ci/codeql/queries/temp.ql hashes to ee3775447dac1b680f615a0ea9e043e0cee8b0b5.
[2023-01-07 18:24:07] [DETAILS] execute query-server2> Compilation cache hit for /Users/me/workspace/project1/server/infrastructure/ci/codeql/queries/temp.ql.
[2023-01-07 18:24:07] [PROGRESS] execute query-server2> No database upgrade/downgrade needed for /Users/me/workspace/project1/server/infrastructure/ci/codeql/queries/temp.ql
[2023-01-07 18:24:07] Calling plumbing command: codeql resolve extensions --search-path= --additional-packs=/Users/me/workspace/project1/server --insecurely-execute-ml-model-checksums= /Users/me/workspace/project1/server/infrastructure/ci/codeql/queries
[2023-01-07 18:24:07] Calling plumbing command: codeql resolve queries --search-path=/ --additional-packs=/Users/me/workspace/project1/server --qlconfig-file=/qlconfig.yml --format startingpacks -- /Users/me/workspace/project1/server/infrastructure/ci/codeql/queries
[2023-01-07 18:24:07] [PROGRESS] resolve queries> Recording pack reference project1/server at /Users/me/workspace/project1/server/infrastructure/ci/codeql.
[2023-01-07 18:24:07] [SPAMMY] resolve queries> Scanning for QL files at /Users/me/workspace/project1/server/infrastructure/ci/codeql/queries.
[2023-01-07 18:24:07] [SPAMMY] resolve queries> Found 12 QL files in /Users/me/workspace/project1/server/infrastructure/ci/codeql/queries.
[2023-01-07 18:24:07] Plumbing command codeql resolve queries completed:
                      [
                        "/Users/me/workspace/project1/server/infrastructure/ci/codeql"
                      ]
[2023-01-07 18:24:07] [PROGRESS] execute query-server2> Error running query
[2023-01-07 18:24:07] [ERROR] Error running query
                              com.semmle.util.exception.ResourceError: Could not list directory /System/Volumes/Data/private/var/folders/8q/s4xrp_nj3697vymtw3d1gjwr0000gn/T/AppTranslocation/BB24E746-B84C-482C-AC7F-76ABFBC5F809: java.nio.file.FileSystemException: /System/Volumes/Data/private/var/folders/8q/s4xrp_nj3697vymtw3d1gjwr0000gn/T/AppTranslocation/BB24E746-B84C-482C-AC7F-76ABFBC5F809: Result too large
                              	at com.semmle.frontend.packs.DiskFileSystem.directChildren(DiskFileSystem.java:66)
                              	at com.semmle.frontend.packs.glob.PathMatchTreeWalker.pushStackEntry(PathMatchTreeWalker.java:340)
                              	at com.semmle.frontend.packs.glob.PathMatchTreeWalker.matchDirectory(PathMatchTreeWalker.java:198)
                              	at com.semmle.frontend.packs.glob.PathMatchTreeWalker.walk(PathMatchTreeWalker.java:119)
                              	at com.semmle.frontend.packs.glob.PathMatcher.walkFileTree(PathMatcher.java:274)
                              	at com.semmle.frontend.packs.ScanByManifests.scanTree(ScanByManifests.java:399)
                              	at com.semmle.frontend.packs.ScanByManifests.scanForPacksAndWorkspaces(ScanByManifests.java:154)
                              	at com.semmle.frontend.packs.QlPackResolver.scanForPacksAndWorkspaces(QlPackResolver.java:88)
                              	at com.semmle.frontend.packs.QlPackContainer.computePacksAndWorkspaces(QlPackContainer.java:115)
                              	at com.semmle.frontend.packs.QlPackContainer.lambda$new$0(QlPackContainer.java:39)
                              	at com.semmle.api.compilation.CachedOperation.get(CachedOperation.java:72)
                              	at com.semmle.frontend.packs.QlPackContainer.findPacksByName(QlPackContainer.java:70)
                              	at com.semmle.frontend.packs.QlPackSearchContext.findPacksByName(QlPackSearchContext.java:615)
                              	at com.semmle.frontend.packs.QlPackSearchContext.doResolutionByName(QlPackSearchContext.java:544)
                              	at com.semmle.frontend.packs.QlPackSearchContext.findPackByVersion(QlPackSearchContext.java:360)
                              	at com.semmle.frontend.packs.QlPackSearchContext.lambda$findAllPackDependencies$18(QlPackSearchContext.java:432)
                              	at java.base/java.util.Optional.orElseGet(Unknown Source)
                              	at com.semmle.frontend.packs.QlPackSearchContext.lambda$findAllPackDependencies$19(QlPackSearchContext.java:422)
                              	at java.base/java.util.Optional.map(Unknown Source)
                              	at com.semmle.frontend.packs.QlPackSearchContext.findAllPackDependencies(QlPackSearchContext.java:403)
                              	at com.semmle.cli2.resolve.ResolveExtensionsCommand.resolvePackDependencies(ResolveExtensionsCommand.java:289)
                              	at com.semmle.cli2.resolve.ResolveExtensionsCommand.executeJSON(ResolveExtensionsCommand.java:75)
                              	at com.semmle.cli2.resolve.ResolveExtensionsCommand.executeJSON(ResolveExtensionsCommand.java:47)
                              	at com.semmle.cli2.picocli.SimpleJsonSubcommand.executeInsistingOnJSONWithExistingMessages(SimpleJsonSubcommand.java:129)
                              	at com.semmle.cli2.picocli.SubcommandCommon.withCompilationMessages(SubcommandCommon.java:405)
                              	at com.semmle.cli2.picocli.SimpleJsonSubcommand.executeInsistingOnJSON(SimpleJsonSubcommand.java:119)
                              	at com.semmle.cli2.picocli.PlumbingRunner.call(PlumbingRunner.java:54)
                              	at com.semmle.cli2.picocli.SubcommandCommon.callPlumbingInProcess(SubcommandCommon.java:150)
                              	at com.semmle.cli2.execute.queryServer2.QueryServer2Command$Impl.resolveExtensions(QueryServer2Command.java:286)
                              	at com.semmle.cli2.execute.queryServer2.QueryServer2Command$Impl.compileAndPrepareQuery(QueryServer2Command.java:432)
                              	at com.semmle.cli2.execute.queryServer2.QueryServer2Command$Impl.lambda$runQuery$26(QueryServer2Command.java:465)
                              	at com.semmle.util.concurrent.FutureUtils.supplyCompose(FutureUtils.java:217)
                              	at com.semmle.cli2.execute.queryServer2.QueryServer2Command$Impl.lambda$runQuery$28(QueryServer2Command.java:457)
                              	at com.semmle.cli2.execute.queryServer2.QueryServer2Command$Impl.lambda$withProgressAndCancellation$15(QueryServer2Command.java:346)
                              	at com.semmle.util.concurrent.FutureUtils.supplyCompose(FutureUtils.java:217)
                              	at com.semmle.cli2.execute.queryServer2.QueryServer2Command$Impl.lambda$withProgressAndCancellation$16(QueryServer2Command.java:346)
                              	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
                              	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
                              	at java.base/java.lang.Thread.run(Unknown Source)
Jan 07, 2023 6:24:07 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: Could not list directory /System/Volumes/Data/private/var/folders/8q/s4xrp_nj3697vymtw3d1gjwr0000gn/T/AppTranslocation/BB24E746-B84C-482C-AC7F-76ABFBC5F809: java.nio.file.FileSystemException: /System/Volumes/Data/private/var/folders/8q/s4xrp_nj3697vymtw3d1gjwr0000gn/T/AppTranslocation/BB24E746-B84C-482C-AC7F-76ABFBC5F809: Result too large
java.util.concurrent.CompletionException: Could not list directory /System/Volumes/Data/private/var/folders/8q/s4xrp_nj3697vymtw3d1gjwr0000gn/T/AppTranslocation/BB24E746-B84C-482C-AC7F-76ABFBC5F809: java.nio.file.FileSystemException: /System/Volumes/Data/private/var/folders/8q/s4xrp_nj3697vymtw3d1gjwr0000gn/T/AppTranslocation/BB24E746-B84C-482C-AC7F-76ABFBC5F809: Result too large
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionallyStage(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.exceptionally(Unknown Source)
	at com.semmle.cli2.execute.queryServer2.QueryServer2Command$Impl.lambda$runQuery$28(QueryServer2Command.java:503)
	at com.semmle.cli2.execute.queryServer2.QueryServer2Command$Impl.lambda$withProgressAndCancellation$15(QueryServer2Command.java:346)
	at com.semmle.util.concurrent.FutureUtils.supplyCompose(FutureUtils.java:217)
	at com.semmle.cli2.execute.queryServer2.QueryServer2Command$Impl.lambda$withProgressAndCancellation$16(QueryServer2Command.java:346)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: Could not list directory /System/Volumes/Data/private/var/folders/8q/s4xrp_nj3697vymtw3d1gjwr0000gn/T/AppTranslocation/BB24E746-B84C-482C-AC7F-76ABFBC5F809: java.nio.file.FileSystemException: /System/Volumes/Data/private/var/folders/8q/s4xrp_nj3697vymtw3d1gjwr0000gn/T/AppTranslocation/BB24E746-B84C-482C-AC7F-76ABFBC5F809: Result too large
	at com.semmle.frontend.packs.DiskFileSystem.directChildren(DiskFileSystem.java:66)
	at com.semmle.frontend.packs.glob.PathMatchTreeWalker.pushStackEntry(PathMatchTreeWalker.java:340)
	at com.semmle.frontend.packs.glob.PathMatchTreeWalker.matchDirectory(PathMatchTreeWalker.java:198)
	at com.semmle.frontend.packs.glob.PathMatchTreeWalker.walk(PathMatchTreeWalker.java:119)
	at com.semmle.frontend.packs.glob.PathMatcher.walkFileTree(PathMatcher.java:274)
	at com.semmle.frontend.packs.ScanByManifests.scanTree(ScanByManifests.java:399)
	at com.semmle.frontend.packs.ScanByManifests.scanForPacksAndWorkspaces(ScanByManifests.java:154)
	at com.semmle.frontend.packs.QlPackResolver.scanForPacksAndWorkspaces(QlPackResolver.java:88)
	at com.semmle.frontend.packs.QlPackContainer.computePacksAndWorkspaces(QlPackContainer.java:115)
	at com.semmle.frontend.packs.QlPackContainer.lambda$new$0(QlPackContainer.java:39)
	at com.semmle.api.compilation.CachedOperation.get(CachedOperation.java:72)
	at com.semmle.frontend.packs.QlPackContainer.findPacksByName(QlPackContainer.java:70)
	at com.semmle.frontend.packs.QlPackSearchContext.findPacksByName(QlPackSearchContext.java:615)
	at com.semmle.frontend.packs.QlPackSearchContext.doResolutionByName(QlPackSearchContext.java:544)
	at com.semmle.frontend.packs.QlPackSearchContext.findPackByVersion(QlPackSearchContext.java:360)
	at com.semmle.frontend.packs.QlPackSearchContext.lambda$findAllPackDependencies$18(QlPackSearchContext.java:432)
	at java.base/java.util.Optional.orElseGet(Unknown Source)
	at com.semmle.frontend.packs.QlPackSearchContext.lambda$findAllPackDependencies$19(QlPackSearchContext.java:422)
	at java.base/java.util.Optional.map(Unknown Source)
	at com.semmle.frontend.packs.QlPackSearchContext.findAllPackDependencies(QlPackSearchContext.java:403)
	at com.semmle.cli2.resolve.ResolveExtensionsCommand.resolvePackDependencies(ResolveExtensionsCommand.java:289)
	at com.semmle.cli2.resolve.ResolveExtensionsCommand.executeJSON(ResolveExtensionsCommand.java:75)
	at com.semmle.cli2.resolve.ResolveExtensionsCommand.executeJSON(ResolveExtensionsCommand.java:47)
	at com.semmle.cli2.picocli.SimpleJsonSubcommand.executeInsistingOnJSONWithExistingMessages(SimpleJsonSubcommand.java:129)
	at com.semmle.cli2.picocli.SubcommandCommon.withCompilationMessages(SubcommandCommon.java:405)
	at com.semmle.cli2.picocli.SimpleJsonSubcommand.executeInsistingOnJSON(SimpleJsonSubcommand.java:119)
	at com.semmle.cli2.picocli.PlumbingRunner.call(PlumbingRunner.java:54)
	at com.semmle.cli2.picocli.SubcommandCommon.callPlumbingInProcess(SubcommandCommon.java:150)
	at com.semmle.cli2.execute.queryServer2.QueryServer2Command$Impl.resolveExtensions(QueryServer2Command.java:286)
	at com.semmle.cli2.execute.queryServer2.QueryServer2Command$Impl.compileAndPrepareQuery(QueryServer2Command.java:432)
	at com.semmle.cli2.execute.queryServer2.QueryServer2Command$Impl.lambda$runQuery$26(QueryServer2Command.java:465)
	at com.semmle.util.concurrent.FutureUtils.supplyCompose(FutureUtils.java:217)
	at com.semmle.cli2.execute.queryServer2.QueryServer2Command$Impl.lambda$runQuery$28(QueryServer2Command.java:457)
	... 6 more

Error running query: Internal error. (codeQL.runQuery)
Error: Error running query: Internal error.
    at handleResponse (/Users/me/.vscode/extensions/github.vscode-codeql-1.7.7/node_modules/vscode-jsonrpc/lib/common/connection.js:531:48)
    at processMessageQueue (/Users/me/.vscode/extensions/github.vscode-codeql-1.7.7/node_modules/vscode-jsonrpc/lib/common/connection.js:327:17)
    at Immediate.<anonymous> (/Users/me/.vscode/extensions/github.vscode-codeql-1.7.7/node_modules/vscode-jsonrpc/lib/common/connection.js:311:13)
    at processImmediate (node:internal/timers:466:21)
```

Thank you :)

**Comment by aeisenberg** [comment]
This is the important part of the message: `SEVERE: Internal error: Could not list directory /System/Volumes/Data/private/var/folders/8q/s4xrp_nj3697vymtw3d1gjwr0000gn/T/AppTranslocation/BB24E746-B84C-482C-AC7F-76ABFBC5F809: java.nio.file.FileSystemException: /System/Volumes/Data/private/var/folders/8q/s4xrp_nj3697vymtw3d1gjwr0000gn/T/AppTranslocation/BB24E746-B84C-482C-AC7F-76ABFBC5F809: Result too large`

The `AppTranslocation` "Result too large" message is coming from the OS. This generally means that there is not enough space to write a file in the location that the OS wants to. Eg- https://discussions.apple.com/thread/974231 However in this case, it is happening while the directory tree is being walked, looking for files relevant to codeql. 

[Looking at this link](https://lapcatsoftware.com/articles/app-translocation.html), it suggests there might be a Gatekeeper issue going on. Perhaps try (temporarily) disabling gatekeeper and see if that works?

**Comment by Nikoms** [comment]
Thank you very much for your answer @aeisenberg. I tried to disable Gatekeeper but didn't work. However, I re-retry to uninstall vscode and delete more folders than last time, and it's working now. 

Thank you for your help again 🙏
