### ISSUE TITLE
All queries finish with same error

### ISSUE THREAD

**Issue by kazarart** [github/vscode-codeql#2545]
```
2023-06-26 02:46:09] [ERROR] Error running query
                              java.util.concurrent.CompletionException: Error acquiring the IMB cache lock at path /home/user/Desktop/lab_sast/exif-database/db-cpp/default/cache/.lock
                              (eventual cause: FileNotFoundException "/home/user/Desktop/lab_sast/exif-database/db-cpp/default/cache/.lock (Permission denied)")
                              	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
                              	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
                              	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
                              	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
                              	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
                              	at com.semmle.cli2.execute.queryServer2.QueryServer2BackendManager$WaitingEntry.lambda$error$1(QueryServer2BackendManager.java:221)
                              	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
                              	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
                              	at java.base/java.lang.Thread.run(Unknown Source)
                              Caused by: com.semmle.util.exception.ResourceError: Error acquiring the IMB cache lock at path /home/user/Desktop/lab_sast/exif-database/db-cpp/default/cache/.lock
                              (eventual cause: FileNotFoundException "/home/user/Desktop/lab_sast/exif-database/db-cpp/default/cache/.lock (Permission denied)")
                              	at com.semmle.inmemory.caching.RelationCacheImpl.takeFilesystemLock(RelationCacheImpl.java:352)
                              	at com.semmle.inmemory.caching.RelationCacheImpl.create(RelationCacheImpl.java:111)
                              	at com.semmle.inmemory.scheduler.EvaluationSchedule.<init>(EvaluationSchedule.java:93)
                              	at com.semmle.inmemory.caching.RelationManager.<init>(RelationManager.java:68)
                              	at com.semmle.inmemory.MemoryBackend.<init>(MemoryBackend.java:132)
                              	at com.semmle.cli2.ql.EvaluationCommon.<init>(EvaluationCommon.java:85)
                              	at com.semmle.cli2.execute.queryServer2.QueryServer2BackendManager.createBackend(QueryServer2BackendManager.java:190)
                              	at com.semmle.cli2.execute.queryServer2.QueryServer2BackendManager$WaitingEntry.create(QueryServer2BackendManager.java:213)
                              	at com.semmle.cli2.execute.queryServer2.QueryServer2BackendManager.scheduleUnblockedTasks(QueryServer2BackendManager.java:263)
                              	at com.semmle.cli2.execute.queryServer2.QueryServer2BackendManager.withDB(QueryServer2BackendManager.java:173)
                              	at com.semmle.cli2.execute.queryServer2.QueryServer2BackendManager.withDBShared(QueryServer2BackendManager.java:71)
                              	at com.semmle.cli2.execute.queryServer2.QueryServer2Command$Impl.lambda$runQuery$26(QueryServer2Command.java:556)
                              	at com.semmle.util.concurrent.FutureUtils.supplyCompose(FutureUtils.java:248)
                              	at com.semmle.cli2.execute.queryServer2.QueryServer2Command$Impl.lambda$runQuery$28(QueryServer2Command.java:537)
                              	at com.semmle.cli2.execute.queryServer2.QueryServer2Command$Impl.lambda$withProgressAndCancellation$15(QueryServer2Command.java:397)
                              	at com.semmle.util.concurrent.FutureUtils.supplyCompose(FutureUtils.java:248)
                              	at com.semmle.cli2.execute.queryServer2.QueryServer2Command$Impl.lambda$withProgressAndCancellation$16(QueryServer2Command.java:396)
                              	... 3 common frames omitted
                              Caused by: com.semmle.util.exception.ResourceError: Could not create lock file at /home/user/Desktop/lab_sast/exif-database/db-cpp/default/cache/.lock - the parent directory likely does not exist.
                              (eventual cause: FileNotFoundException "/home/user/Desktop/lab_sast/exif-database/db-cpp/default/cache/.lock (Permission denied)")
                              	at com.semmle.util.files.FileSystemLock.<init>(FileSystemLock.java:64)
                              	at com.semmle.inmemory.caching.RelationCacheImpl.takeFilesystemLock(RelationCacheImpl.java:350)
                              	... 19 common frames omitted
                              Caused by: java.io.FileNotFoundException: /home/user/Desktop/lab_sast/exif-database/db-cpp/default/cache/.lock (Permission denied)
                              	at java.base/java.io.RandomAccessFile.open0(Native Method)
                              	at java.base/java.io.RandomAccessFile.open(Unknown Source)
                              	at java.base/java.io.RandomAccessFile.<init>(Unknown Source)
                              	at java.base/java.io.RandomAccessFile.<init>(Unknown Source)
                              	at com.semmle.util.files.FileSystemLock.<init>(FileSystemLock.java:62)
                              	... 20 common frames omitted
Jun 26, 2023 2:46:09 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: Error acquiring the IMB cache lock at path /home/user/Desktop/lab_sast/exif-database/db-cpp/default/cache/.lock
(eventual cause: FileNotFoundException "/home/user/Desktop/lab_sast/exif-database/db-cpp/default/cache/.lock (Permission denied)")
java.util.concurrent.CompletionException: Error acquiring the IMB cache lock at path /home/user/Desktop/lab_sast/exif-database/db-cpp/default/cache/.lock
(eventual cause: FileNotFoundException "/home/user/Desktop/lab_sast/exif-database/db-cpp/default/cache/.lock (Permission denied)")
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at com.semmle.cli2.execute.queryServer2.QueryServer2BackendManager$WaitingEntry.lambda$error$1(QueryServer2BackendManager.java:221)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: Error acquiring the IMB cache lock at path /home/user/Desktop/lab_sast/exif-database/db-cpp/default/cache/.lock
(eventual cause: FileNotFoundException "/home/user/Desktop/lab_sast/exif-database/db-cpp/default/cache/.lock (Permission denied)")
	at com.semmle.inmemory.caching.RelationCacheImpl.takeFilesystemLock(RelationCacheImpl.java:352)
	at com.semmle.inmemory.caching.RelationCacheImpl.create(RelationCacheImpl.java:111)
	at com.semmle.inmemory.scheduler.EvaluationSchedule.<init>(EvaluationSchedule.java:93)
	at com.semmle.inmemory.caching.RelationManager.<init>(RelationManager.java:68)
	at com.semmle.inmemory.MemoryBackend.<init>(MemoryBackend.java:132)
	at com.semmle.cli2.ql.EvaluationCommon.<init>(EvaluationCommon.java:85)
	at com.semmle.cli2.execute.queryServer2.QueryServer2BackendManager.createBackend(QueryServer2BackendManager.java:190)
	at com.semmle.cli2.execute.queryServer2.QueryServer2BackendManager$WaitingEntry.create(QueryServer2BackendManager.java:213)
	at com.semmle.cli2.execute.queryServer2.QueryServer2BackendManager.scheduleUnblockedTasks(QueryServer2BackendManager.java:263)
	at com.semmle.cli2.execute.queryServer2.QueryServer2BackendManager.withDB(QueryServer2BackendManager.java:173)
	at com.semmle.cli2.execute.queryServer2.QueryServer2BackendManager.withDBShared(QueryServer2BackendManager.java:71)
	at com.semmle.cli2.execute.queryServer2.QueryServer2Command$Impl.lambda$runQuery$26(QueryServer2Command.java:556)
	at com.semmle.util.concurrent.FutureUtils.supplyCompose(FutureUtils.java:248)
	at com.semmle.cli2.execute.queryServer2.QueryServer2Command$Impl.lambda$runQuery$28(QueryServer2Command.java:537)
	at com.semmle.cli2.execute.queryServer2.QueryServer2Command$Impl.lambda$withProgressAndCancellation$15(QueryServer2Command.java:397)
	at com.semmle.util.concurrent.FutureUtils.supplyCompose(FutureUtils.java:248)
	at com.semmle.cli2.execute.queryServer2.QueryServer2Command$Impl.lambda$withProgressAndCancellation$16(QueryServer2Command.java:396)
	... 3 more
Caused by: Could not create lock file at /home/user/Desktop/lab_sast/exif-database/db-cpp/default/cache/.lock - the parent directory likely does not exist.
(eventual cause: FileNotFoundException "/home/user/Desktop/lab_sast/exif-database/db-cpp/default/cache/.lock (Permission denied)")
	at com.semmle.util.files.FileSystemLock.<init>(FileSystemLock.java:64)
	at com.semmle.inmemory.caching.RelationCacheImpl.takeFilesystemLock(RelationCacheImpl.java:350)
	... 19 more
Caused by: java.io.FileNotFoundException: /home/user/Desktop/lab_sast/exif-database/db-cpp/default/cache/.lock (Permission denied)
	at java.base/java.io.RandomAccessFile.open0(Native Method)
	at java.base/java.io.RandomAccessFile.open(Unknown Source)
	at java.base/java.io.RandomAccessFile.<init>(Unknown Source)
	at java.base/java.io.RandomAccessFile.<init>(Unknown Source)
	at com.semmle.util.files.FileSystemLock.<init>(FileSystemLock.java:62)
	... 20 more

Error running query: Internal error. (codeQL.runQueries)
Error: Error running query: Internal error.
    at handleResponse (/home/user/.vscode/extensions/github.vscode-codeql-1.8.6/out/extension.js:4434:40)
    at processMessageQueue (/home/user/.vscode/extensions/github.vscode-codeql-1.8.6/out/extension.js:4257:13)
    at Immediate.<anonymous> (/home/user/.vscode/extensions/github.vscode-codeql-1.8.6/out/extension.js:4243:11)
    at processImmediate (node:internal/timers:466:21)

```
Codeql v1.8.6
Vscode Version: 1.78.2

**Comment by kazarart** [comment]
Database folder was owned be root, but vscode was started under non-root user. That's why error appeared

**Comment by kazarart** [comment]
Database folder was owned be root, but vscode was started under non-root user. That's why error appeared
