### ISSUE TITLE
Bug: Error when trying to open query log file (on Windows)

### ISSUE THREAD

**Issue by shati-patel** [github/vscode-codeql#314]
### Describe the bug

The right-click query history option **Show Query Log** doesn't work for me. I get the following error:

```
Could not open log file c:\Users\Shati Patel\AppData\Roaming\Code\User\workspaceStorage\f69b706cc42093b6075931e719082fad\GitHub.vscode-codeql\CodeQL Query Server\query-test.ql-1.log
cannot open c:%5CUsers%5CShati%20Patel%5CAppData%5CRoaming%5CCode%5CUser%5CworkspaceStorage%5Cf69b706cc42093b6075931e719082fad%5CGitHub.vscode-codeql%5CCodeQL%20Query%20Server%5Cquery-test.ql-1.log. Detail: resource is not available
Error: cannot open c:%5CUsers%5CShati%20Patel%5CAppData%5CRoaming%5CCode%5CUser%5CworkspaceStorage%5Cf69b706cc42093b6075931e719082fad%5CGitHub.vscode-codeql%5CCodeQL%20Query%20Server%5Cquery-test.ql-1.log. Detail: resource is not available
    at file:///C:/Users/Shati Patel/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4156:737
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

### Additional context
Running v.1.1.1 of the extension on Windows.

**Comment by aeisenberg** [comment]
Able to reproduce this on my vm. The file path itself is correct. When I copy the full path of the file from the logs and paste it into the file explorer, I can open it. So, it must be some kind of encoding issue.
