### ISSUE TITLE
Sorting in the result viewer doesn't work with pagination.

### ISSUE THREAD

**Issue by aschackmull** [github/vscode-codeql#586]
**Describe the bug**
If I click a column in the result viewer to sort and then click to the next page of results, then the sorting is no longer applied.

**To Reproduce**
I can currently reproduce by running
```ql
from int x, int y
where x in [1..15] and y in [1..15]
select x, y
```
and sorting on `y`. Then the results are no longer sorted when I go to page 2.

**Expected behavior**
Once results are sorted by a specific column I expect that sorting to be respected across several pages of results.

**Comment by aeisenberg** [comment]
Your example above seems to work fine for me, but I do see the behaviour when I run this query:

```ql
from int x, int y, int z
where x = [0..15] and y = [0..15] and z = x*y
select x, y, z
```

And, as you describe in slack, here is how to reproduce:

1. Run query
2. Sort on x descending.
3. Go to page 2 of the results.

**Comment by aeisenberg** [comment]
All right. Here's what I have so far. It is looking like a problem with the bqrs decoder, which is surprising since I would think this is a well-trod area of the cli.

The extension generates and caches a sorted version of the BQRS each time the results page is resorted. 

For example, when you first click on a column header, it calls this command:

```codeql bqrs info sortedResults0-#select.bqrs --format=json  --paginate-rows=100```

Among other things, this returns a list of byte offsets for page boundaries, assuming 100 rows per page. Eg:

```json
     "pagination" : {
        "step-size" : 100,
        "offsets" : [
          21,
          321,
          692
        ]
      }
```

Next, the following command is called to cache the current sort state in a second bqrs file:

```
codeql bqrs decode --format=bqrs --result-set=#select --output=sortedResults0-#select.bqrs --sort-key=2 --sort-direction=asc results0.bqrs
```
Finally, the proper page-aware call is made, which takes the byte offset discovered earlier and the requested page size:

```
codeql bqrs decode --entities=url,string --result-set "#select" --rows 100 --start-at 321 "sortedResults0-#select.bqrs" 
```

However, when I get to page 3, I often see the exception spit in the debug console:

```
rejected promise not handled within 1 second: Error: Reading bqrs data failed: A fatal error occurred: Binary decoder reached end of stream while expecting byte
[2020-09-28 14:16:52] Exception caught at top level: Binary decoder reached end of stream while expecting byte
                      com.semmle.api.result.BinaryDecoder.readByte(BinaryDecoder.java:48)
                      com.semmle.api.result.BinaryDecoder.decodeULEB128(BinaryDecoder.java:84)
                      com.semmle.api.result.QueryResultsReader.decodeInt(QueryResultsReader.java:19)
                      com.semmle.api.result.ResultArranger$IntegerResultColumn.decode(ResultArranger.java:141)
                      com.semmle.api.result.ResultArranger$IntegerResultColumn.decode(ResultArranger.java:132)
                      com.semmle.api.result.ResultArranger.decode(ResultArranger.java:449)
                      com.semmle.api.result.BinaryQueryResultSet$Stream.next(BinaryQueryResultSet.java:647)
                      com.semmle.api.result.BinaryQueryResultSet$Stream.next(BinaryQueryResultSet.java:602)
                      com.semmle.api.result.CroppedResultStream.next(CroppedResultStream.java:31)
                      com.semmle.api.result.CroppedResultStream.next(CroppedResultStream.java:8)
                      com.semmle.cli2.bqrs.DecodeCommand.generateJsonForResultSet(DecodeCommand.java:436)
                      com.semmle.cli2.bqrs.DecodeCommand.lambda$null$2(DecodeCommand.java:277)
                      com.semmle.cli2.bqrs.DecodeCommand.writeJson(DecodeCommand.java:397)
                      com.semmle.cli2.bqrs.DecodeCommand.lambda$generate$3(DecodeCommand.java:277)
                      com.semmle.cli2.bqrs.DecodeCommand.streamOnceUnsorted(DecodeCommand.java:342)
                      com.semmle.cli2.bqrs.DecodeCommand.streamResultSet(DecodeCommand.java:326)
                      com.semmle.cli2.bqrs.DecodeCommand.generate(DecodeCommand.java:274)
                      com.semmle.cli2.bqrs.DecodeCommand.generateOutput(DecodeCommand.java:237)
                      com.semmle.cli2.bqrs.DecodeCommand.executeSubcommand(DecodeCommand.java:210)
                      com.semmle.cli2.picocli.SubcommandCommon.executeWithParent(SubcommandCommon.java:414)
                      com.semmle.cli2.execute.CliServerCommand.lambda$executeSubcommand$0(CliServerCommand.java:67)
                      com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:182)
                      com.semmle.cli2.execute.CliServerCommand.executeSubcommand(CliServerCommand.java:67)
                      com.semmle.cli2.picocli.SubcommandCommon.call(SubcommandCommon.java:430)
                      com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:182)
                      com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:190)
                      com.semmle.cli2.CodeQL.main(CodeQL.java:89)

 extensionHostProcess.js
stack trace: Error: Reading bqrs data failed: A fatal error occurred: Binary decoder reached end of stream while expecting byte
[2020-09-28 14:16:52] Exception caught at top level: Binary decoder reached end of stream while expecting byte
                      com.semmle.api.result.BinaryDecoder.readByte(BinaryDecoder.java:48)
                      com.semmle.api.result.BinaryDecoder.decodeULEB128(BinaryDecoder.java:84)
                      com.semmle.api.result.QueryResultsReader.decodeInt(QueryResultsReader.java:19)
                      com.semmle.api.result.ResultArranger$IntegerResultColumn.decode(ResultArranger.java:141)
                      com.semmle.api.result.ResultArranger$IntegerResultColumn.decode(ResultArranger.java:132)
                      com.semmle.api.result.ResultArranger.decode(ResultArranger.java:449)
                      com.semmle.api.result.BinaryQueryResultSet$Stream.next(BinaryQueryResultSet.java:647)
                      com.semmle.api.result.BinaryQueryResultSet$Stream.next(BinaryQueryResultSet.java:602)
                      com.semmle.api.result.CroppedResultStream.next(CroppedResultStream.java:31)
                      com.semmle.api.result.CroppedResultStream.next(CroppedResultStream.java:8)
                      com.semmle.cli2.bqrs.DecodeCommand.generateJsonForResultSet(DecodeCommand.java:436)
                      com.semmle.cli2.bqrs.DecodeCommand.lambda$null$2(DecodeCommand.java:277)
                      com.semmle.cli2.bqrs.DecodeCommand.writeJson(DecodeCommand.java:397)
                      com.semmle.cli2.bqrs.DecodeCommand.lambda$generate$3(DecodeCommand.java:277)
                      com.semmle.cli2.bqrs.DecodeCommand.streamOnceUnsorted(DecodeCommand.java:342)
                      com.semmle.cli2.bqrs.DecodeCommand.streamResultSet(DecodeCommand.java:326)
                      com.semmle.cli2.bqrs.DecodeCommand.generate(DecodeCommand.java:274)
                      com.semmle.cli2.bqrs.DecodeCommand.generateOutput(DecodeCommand.java:237)
                      com.semmle.cli2.bqrs.DecodeCommand.executeSubcommand(DecodeCommand.java:210)
                      com.semmle.cli2.picocli.SubcommandCommon.executeWithParent(SubcommandCommon.java:414)
                      com.semmle.cli2.execute.CliServerCommand.lambda$executeSubcommand$0(CliServerCommand.java:67)
                      com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:182)
                      com.semmle.cli2.execute.CliServerCommand.executeSubcommand(CliServerCommand.java:67)
                      com.semmle.cli2.picocli.SubcommandCommon.call(SubcommandCommon.java:430)
                      com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:182)
                      com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:190)
                      com.semmle.cli2.CodeQL.main(CodeQL.java:89)

    at CodeQLCliServer.runCodeQlCliInternal (/Users/andrew.eisenberg/Eclipse/git-repos/github/vscode-codeql/extensions/ql-vscode/src/cli.ts:261:15)
    at CodeQLCliServer.runJsonCodeQlCliCommand (/Users/andrew.eisenberg/Eclipse/git-repos/github/vscode-codeql/extensions/ql-vscode/src/cli.ts:412:20)
    at CodeQLCliServer.bqrsDecode (/Users/andrew.eisenberg/Eclipse/git-repos/github/vscode-codeql/extensions/ql-vscode/src/cli.ts:525:12)
    at InterfaceManager.showPageOfRawResults (/Users/andrew.eisenberg/Eclipse/git-repos/github/vscode-codeql/extensions/ql-vscode/src/interface.ts:485:19)
    at InterfaceManager.handleMsgFromView (/Users/andrew.eisenberg/Eclipse/git-repos/github/vscode-codeql/extensions/ql-vscode/src/interface.ts:267:11)
 extensionHostProcess.js
```

**Comment by aeisenberg** [comment]
OK. It's not a bug with bqrs parsing (whew!). The issue is that the extension is running `bqrs info` on the raw (unsorted) results and then running `bqrs decode` on the sorted results. The byte offsets discovered in the `bqrs info` results will be slightly off. 

The solution is to always ensure we are calling `bqrs info` on the sorted results file.
