### ISSUE TITLE
compatibility issue with latest codeql-cli-libraries and codeql vscode extension

### ISSUE THREAD

**Issue by lcwj3** [github/vscode-codeql#787]
**Describe the bug**
Can not run queries on database that is created by latest codeql-cli-libraries (v2.4.5) with latest codeql vscode extension (v1.4.3) 

**To Reproduce**
Create a database with codeql-cli-libraries (v2.4.5), and run queries on it in vscode, which has the latest vscode extension (v1.4.3), it reports this and can not run.
```
Resolving database upgrade scripts using CodeQL CLI: resolve upgrades -v --log-to-stderr --format json --additional-packs /home/chengwei/codes/codeql_call_graph --dbscheme /home/chengwei/codes/express-4.17.1/package/express-db/db-javascript/semmlecode.javascript.dbscheme --target-dbscheme /home/chengwei/codes/codeql_call_graph/javascript/ql/src/semmlecode.javascript.dbscheme...
CLI command succeeded.
[2021-03-18 21:57:57] [DETAILS] resolve upgrades> Searching for upgrades that apply to fbd45f6b3c6f79d732d0e30a92ea5cee438a1a3e.
[2021-03-18 21:57:57] [DETAILS] resolve upgrades> Will look for upgrades in /home/chengwei/codes/codeql_call_graph/javascript/upgrades
[2021-03-18 21:57:57] [DETAILS] resolve upgrades> Will look for upgrades in /home/chengwei/codes/codeql_call_graph/python/upgrades
[2021-03-18 21:57:57] [DETAILS] resolve upgrades> Will look for upgrades in /home/chengwei/codes/codeql_call_graph/java/upgrades
[2021-03-18 21:57:57] [DETAILS] resolve upgrades> Will look for upgrades in /home/chengwei/codes/codeql_call_graph/csharp/upgrades
[2021-03-18 21:57:57] [DETAILS] resolve upgrades> Will look for upgrades in /home/chengwei/codes/codeql_call_graph/cpp/upgrades
[2021-03-18 21:57:57] [DETAILS] resolve upgrades> Will look for upgrades in /home/chengwei/.config/Code/User/globalStorage/github.vscode-codeql/distribution1/codeql/legacy-upgrades/upgrades

Query /home/chengwei/codes/codeql_call_graph/javascript/ql/examples/snippets/retrieve_export_modules.ql expects database scheme /home/chengwei/codes/codeql_call_graph/javascript/ql/src/semmlecode.javascript.dbscheme, but the current database has a different scheme, and no database upgrades are available. The current database scheme may be newer than the CodeQL query libraries in your workspace.

Please try using a newer version of the query libraries. (codeQL.runQuery)
Error: Query /home/chengwei/codes/codeql_call_graph/javascript/ql/examples/snippets/retrieve_export_modules.ql expects database scheme /home/chengwei/codes/codeql_call_graph/javascript/ql/src/semmlecode.javascript.dbscheme, but the current database has a different scheme, and no database upgrades are available. The current database scheme may be newer than the CodeQL query libraries in your workspace.

Please try using a newer version of the query libraries.
	at reportNoUpgradePath (/home/chengwei/.vscode/extensions/github.vscode-codeql-1.4.3/out/run-queries.js:252:11)
	at compileNonDestructiveUpgrade (/home/chengwei/.vscode/extensions/github.vscode-codeql-1.4.3/out/run-queries.js:265:9)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async Object.compileAndRunQueryAgainstDatabase (/home/chengwei/.vscode/extensions/github.vscode-codeql-1.4.3/out/run-queries.js:434:26)
	at async compileAndRunQuery (/home/chengwei/.vscode/extensions/github.vscode-codeql-1.4.3/out/extension.js:314:26)
	at async ctx.subscriptions.push.commandRunner_1.commandRunnerWithProgress.title (/home/chengwei/.vscode/extensions/github.vscode-codeql-1.4.3/out/extension.js:346:121)
```

**Expected behavior**
run query successfully

**Additional context**
ubuntu 18.04

**Comment by hmakholm** [comment]
Errors of this kind can appear if you upgrade the CLI binaries without also upgrading your checkout of https://github.com/github/codeql -- you should track at least the branch named `lgtm.com` to avoid compatibility problems.

(If you're using the vscode-codeql-starter skeleton, the github/codeql is the `ql` submodule.)

**Comment by lcwj3** [comment]
> Errors of this kind can appear if you upgrade the CLI binaries without also upgrading your checkout of https://github.com/github/codeql -- you should track at least the branch named `lgtm.com` to avoid compatibility problems.
> 
> (If you're using the vscode-codeql-starter skeleton, github/codeql is the `ql` submodule.)

Thanks! I roll back to v2.4.4 and create database again, the error disappeared.
