### ISSUE TITLE
Internal error for malformed CodeQL code

### ISSUE THREAD

**Issue by Marcono1234** [github/vscode-codeql#907]
**Describe the bug**
Certain malformed CodeQL code causes an internal error:
```
{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///#REDACTED#/AppData/Roaming/Code/User/workspaceStorage/3a7e393392e7d51ebb5604839157de07/GitHub.vscode-codeql/quick-queries/quick-query.ql","diagnostics":[{"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":0}},"severity":1,"source":"","message":"An internal error occurred during compilation."}]}}[2021-07-10 23:45:36] [ERROR] Unhandled error in QL frontend
                              java.lang.NullPointerException: null
                              	at com.semmle.util.graph.AdjacencyGraph.edgeLabels(AdjacencyGraph.java:175)
...
```

I also experienced other errors at the same time, but I cannot reproduce them anymore. Here is a more extensive log snippet:
<details>
<summary>Log snippet</summary>

```
{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///#REDACTED#/AppData/Roaming/Code/User/workspaceStorage/3a7e393392e7d51ebb5604839157de07/GitHub.vscode-codeql/quick-queries/quick-query.ql","diagnostics":[{"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":0}},"severity":1,"source":"","message":"An internal error occurred during compilation."}]}}[2021-07-10 23:45:36] [ERROR] Unhandled error in QL frontend
                              java.lang.NullPointerException: null
                              	at com.semmle.util.graph.AdjacencyGraph.edgeLabels(AdjacencyGraph.java:175)
                              	at com.semmle.util.graph.SCC.tarjan(SCC.java:185)
                              	at com.semmle.util.graph.SCC.tarjan(SCC.java:155)
                              	at com.semmle.util.graph.SCC.tarjan(SCC.java:155)
                              	at com.semmle.util.graph.SCC.tarjan(SCC.java:155)
                              	at com.semmle.util.graph.SCC.tarjan(SCC.java:155)
                              	at com.semmle.util.graph.SCC.tarjan(SCC.java:155)
                              	at com.semmle.util.graph.SCC.computeSCCs(SCC.java:113)
                              	at com.semmle.util.graph.SCC.compute(SCC.java:73)
                              	at com.semmle.util.graph.SCC.<init>(SCC.java:39)
                              	at com.semmle.frontend.compiler.codegen.TypeCompiler$SizeDependencies.<init>(TypeCompiler.java:469)
                              	at com.semmle.frontend.compiler.codegen.TypeCompiler.<init>(TypeCompiler.java:70)
                              	at com.semmle.frontend.compiler.CodeGeneration.<init>(CodeGeneration.java:62)
                              	at com.semmle.frontend.compiler.QL2DILCompiler.<init>(QL2DILCompiler.java:47)
                              	at com.semmle.frontend.compiler.QueryCompileTarget$1.<init>(QueryCompileTarget.java:19)
                              	at com.semmle.frontend.compiler.QueryCompileTarget.createCompiler(QueryCompileTarget.java:19)
                              	at com.semmle.frontend.compiler.QLCompileTarget.createPipeline(QLCompileTarget.java:40)
                              	at com.semmle.frontend.server.AsynchronousDiagnosticReporter.doWork(AsynchronousDiagnosticReporter.java:116)
                              	at java.base/java.lang.Thread.run(Unknown Source)
[2021-07-10 23:45:36] Fixed point time time: 00:00.028
[2021-07-10 23:45:36] ReferenceBindingPass ...
[2021-07-10 23:45:36] ReferenceBindingPass time: 00:00.000
[2021-07-10 23:45:36] EntityTypeUpdateBindingPass ...
[2021-07-10 23:45:36] EntityTypeUpdateBindingPass time: 00:00.000
[2021-07-10 23:45:36] DeclarationBindingPass ...
[2021-07-10 23:45:36] DeclarationBindingPass time: 00:00.000
[2021-07-10 23:45:36] PredicateBodyBindingPass ...
[2021-07-10 23:45:36] PredicateBodyBindingPass time: 00:00.054
[2021-07-10 23:45:36] LanguagePragmaPropagationPass ...
[2021-07-10 23:45:36] LanguagePragmaPropagationPass time: 00:00.000
[2021-07-10 23:45:36] Ambiguity checks ...
[2021-07-10 23:45:36] Ambiguity checks time: 00:00.000
[2021-07-10 23:45:36] Ql checks ...
[2021-07-10 23:45:36] Ql checks time: 00:00.033
Jul 10, 2021 11:45:36 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.NullPointerException
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.semmle.frontend.CachingBinder.bindingFor(CachingBinder.java:147)
	at com.semmle.frontend.CachingBinder.getBindingFor(CachingBinder.java:103)
	at com.semmle.frontend.Binder.getBindingFor(Binder.java:60)
	at com.semmle.frontend.project.QLProject.lambda$definition$4(QLProject.java:339)
	... 4 more

Content-Length: 1025

{"jsonrpc":"2.0","id":70,"error":{"code":-32603,"message":"Internal error.","data":"java.util.concurrent.CompletionException: java.lang.NullPointerException\r\n\tat java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)\r\n\tat java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)\r\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\r\n\tat java.base/java.lang.Thread.run(Unknown Source)\r\nCaused by: java.lang.NullPointerException\r\n\tat com.semmle.frontend.CachingBinder.bindingFor(CachingBinder.java:147)\r\n\tat com.semmle.frontend.CachingBinder.getBindingFor(CachingBinder.java:103)\r\n\tat com.semmle.frontend.Binder.getBindingFor(Binder.java:60)\r\n\tat com.semmle.frontend.project.QLProject.lambda$definition$4(QLProject.java:339)\r\n\t... 4 more\r\n"}}[2021-07-10 23:45:36] ExternalModuleBindingPass ...
[Error - 23:45:36] Request textDocument/definition failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.semmle.frontend.CachingBinder.bindingFor(CachingBinder.java:147)
	at com.semmle.frontend.CachingBinder.getBindingFor(CachingBinder.java:103)
	at com.semmle.frontend.Binder.getBindingFor(Binder.java:60)
	at com.semmle.frontend.project.QLProject.lambda$definition$4(QLProject.java:339)
	... 4 more

Content-Length: 141
```

</details>

**Version**
CodeQL extension:
```
CodeQL extension version: 1.5.1 
CodeQL CLI version: 2.5.7 
Platform: win32 x64
```

VSCode:
```
Version: 1.58.0 (user setup)
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-08T06:54:55.083Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19041
```

**To reproduce**
1. Pull CodeQL from https://github.com/Marcono1234/codeql/tree/marcono1234/codeql-cli-internal-error
ℹ️ The code is malformed / incomplete (in `java\ql\src\semmle\code\java\Annotation.qll`)
2. Open it in VSCode
3. Open the file `java\ql\src\semmle\code\java\Type.qll`
4. Look at the "CodeQL Language Server" Output
:x: It shows an internal error

**Expected behavior**
No internal error.

**Comment by adityasharad** [comment]
Thanks! We've got a fix in flight that should be in the next CodeQL release (2.5.8).
