### ISSUE TITLE
"Internal error" when running Quick Evaluation on blank line

### ISSUE THREAD

**Issue by Marcono1234** [github/vscode-codeql#995]
**Describe the bug**
When using the "Quick Evaluation" command while not having selected anything (no text selected and not having clicked on any CodeQL code) an internal error occurs.

- CodeQL Extension Log
    ```
    Internal error. (codeQL.quickEval)
    Error: Internal error.
        at handleResponse (#REDACTED#\.vscode\extensions\github.vscode-codeql-1.5.6\node_modules\vscode-jsonrpc\lib\main.js:449:48)
        at processMessageQueue (#REDACTED#\.vscode\extensions\github.vscode-codeql-1.5.6\node_modules\vscode-jsonrpc\lib\main.js:276:17)
        at Immediate.<anonymous> (#REDACTED#\.vscode\extensions\github.vscode-codeql-1.5.6\node_modules\vscode-jsonrpc\lib\main.js:260:13)
        at processImmediate (internal/timers.js:461:21)
    ```
- CodeQL Query Server
    ```
    Nov 06, 2021 3:05:57 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
    SEVERE: Internal error: com.semmle.util.exception.CatastrophicError: Tried to create negative length position: #REDACTED#\GitHub.vscode-codeql\quick-queries\quick-query.ql:3,1-1,1
    java.util.concurrent.CompletionException: com.semmle.util.exception.CatastrophicError: Tried to create negative length position: #REDACTED#\GitHub.vscode-codeql\quick-queries\quick-query.ql:3,1-1,1
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
        at com.semmle.util.concurrent.FutureUtils.lambda$handleSimple$15(FutureUtils.java:233)
        at java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.handle(Unknown Source)
        at com.semmle.util.concurrent.FutureUtils.handleSimple(FutureUtils.java:231)
        at com.semmle.api.server.QueryServerProgressHelper.lambda$withProgressAndCancellation$1(QueryServerProgressHelper.java:46)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
    Caused by: com.semmle.util.exception.CatastrophicError: Tried to create negative length position: #REDACTED#\GitHub.vscode-codeql\quick-queries\quick-query.ql:3,1-1,1
        at com.semmle.api.compilation.Position.<init>(Position.java:50)
        at com.semmle.api.compilation.Position.<init>(Position.java:39)
        at com.semmle.frontend.compiler.quickeval.QuickEvalCompileTarget.trimPosition(QuickEvalCompileTarget.java:144)
        at com.semmle.frontend.compiler.quickeval.QuickEvalCompileTarget.<init>(QuickEvalCompileTarget.java:64)
        at com.semmle.api.server.CompilationServer.decodeConvertCompilationTarget(CompilationServer.java:306)
        at com.semmle.api.server.CompilationServer.compileToRA(CompilationServer.java:289)
        at com.semmle.api.server.CompilationServer.lambda$compileQuery$2(CompilationServer.java:117)
        at com.semmle.api.server.QueryServerProgressHelper.lambda$null$0(QueryServerProgressHelper.java:47)
        at com.semmle.util.concurrent.FutureUtils.supplyCompose(FutureUtils.java:217)
        at com.semmle.api.server.QueryServerProgressHelper.lambda$withProgressAndCancellation$1(QueryServerProgressHelper.java:47)
        ... 3 more
    ```

**Version**
- Extension
    ```
    CodeQL extension version: 1.5.6 
    CodeQL CLI version: 2.7.0 
    Platform: win32 x64
    ```
- VS Code
    ```
    Version: 1.62.0 (user setup)
    Commit: b3318bc0524af3d74034b8bb8a64df0ccf35549a
    Date: 2021-11-03T15:23:01.379Z
    Electron: 13.5.1
    Chrome: 91.0.4472.164
    Node.js: 14.16.0
    V8: 9.1.269.39-electron.0
    OS: Windows_NT x64 10.0.19043
    ```

**To reproduce**
1. Run "Quick Query"
2. Paste the following as query content
    ```ql
    //
    
    select ""
    ```
3. Place the cursor in the second (blank) line, make a right-click and select "Quick Evaluation"  
:x: An internal error occurs

**Expected behavior**
A regular error should occur, stating that the selected code is not valid for quick evaluation.

**Comment by aeisenberg** [comment]
Thanks for reporting this issue. This is a problem with our query server, not with the vscode extension itself. I'll make the fix there.

**Comment by aeisenberg** [comment]
A fix for this will be available two releases from now. It is too late to get this into 2.7.2, so it will be the release after that.
